version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - consulta-medica-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: mysql:8.0
    container_name: bd
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: consultamedica
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - consulta-medica-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  notificacoes:
    build: ./servico-notificacoes
    container_name: servico-notificacoes
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
      RABBITMQ_TOPIC: sd/notificacoes
      EMAIL_HOST: ${EMAIL_HOST:-smtp.gmail.com}
      EMAIL_PORT: ${EMAIL_PORT:-587}
      EMAIL_SECURE: ${EMAIL_SECURE:-false}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      EMAIL_FROM: ${EMAIL_FROM:-Sistema de Consultas MÃ©dicas <noreply@consultamedica.com>}
      NODE_ENV: production
    networks:
      - consulta-medica-network
    restart: unless-stopped

  pagamentos:
    build: ./servico-pagamentos
    container_name: laravel-api
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: consultamedica
      DB_USERNAME: user
      DB_PASSWORD: userpassword
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASSWORD: admin
      RABBITMQ_VHOST: /
    restart: unless-stopped
    volumes:
      - ./servico-pagamentos:/var/www
    command: sh -c "composer install --no-interaction && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"
    networks:
      - consulta-medica-network

  agendamento:
    build:
      context: ./servico-agendamento
      dockerfile: Dockerfile
    container_name: servico-agendamento
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/consultamedica?createDatabaseIfNotExist=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=userpassword
      - GRPC_SERVER_PORT=9090
      - RABBITMQ_HOST=rabbitmq
      - SERVICE_PAGAMENTOS_URL=http://pagamentos:8000/api/payloads
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - consulta-medica-network
    restart: unless-stopped

  usuario-service:
    build:
      context: ./servico-usuario
      dockerfile: Dockerfile.service
    container_name: servico-usuario
    environment:
      DATABASE_URL: mysql://user:userpassword@db:3306/consultamedica
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: consultamedica
      DB_USER: user
      DB_PASSWORD: userpassword
      RABBITMQ_HOST: rabbitmq
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "5001:5001"
    networks:
      - consulta-medica-network
    restart: unless-stopped

  usuario-interface:
    build:
      context: ./servico-usuario
      dockerfile: Dockerfile.interface
    container_name: servico-usuario-interface
    environment:
      USER_SERVICE_HOST: servico-usuario
      USER_SERVICE_PORT: 5001
    depends_on:
      - usuario-service
    ports:
      - "5000:5000"
    networks:
      - consulta-medica-network
    restart: unless-stopped

volumes:
  rabbitmq_data:
  db_data:


networks:
  consulta-medica-network:
    driver: bridge
