version: "3.8"

services:
  pagamentos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-api
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    networks:
      - consulta-medica-network
    command: php artisan serve --host=0.0.0.0 --port=8000

networks:
  consulta-medica-network:
    driver: bridge
